services:
  server:
    image: mahditalaldev/dockertestlaravel:latest
    environment:
      - LARAVEL_DATABASE_HOST=database
      - LARAVEL_DATABASE_NAME=dockerTest_db
      - LARAVEL_DATABASE_USER=root
      - LARAVEL_DATABASE_PASSWORD=1234
      - LARAVEL_DATABASE_PORT_NUMBER=3306
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=dockerTest_db
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  Node:
    image: mahditalaldev/dockertestlaravelnode:latest
    restart: always
    ports:
      - 3001:3001

  React:
   image: mahditalaldev/dockertestlaravelreact:latest
   restart: always
   ports: 
      - 80:80

volumes:
  db-data:

